name: 機能追加(Feature Request)
description: 機能追加Issue
title: "[FEATUE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 概要
      description: 機能追加概要
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        以下、オプションです。よろしければご記入ください。
  - type: textarea
    id: what-happened
    attributes:
      label: 顧客からの提供資料（Email 内容など）
      description: 
    validations:
      required: false
